# Generated by Django 3.2 on 2022-05-28 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material_data', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cts', 'Cuento'), ('nov', 'Novela'), ('cst', 'Consulta'), ('ctf', 'Cientifico'), ('poe', 'Poesia'), ('bgr', 'Biografico'), ('vjs', 'Viajes')], max_length=3)),
                ('title', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('spa', 'Spanish'), ('en', 'English')], max_length=3)),
                ('number_pages', models.IntegerField()),
                ('size', models.IntegerField()),
                ('description', models.TextField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('year_publication', models.CharField(max_length=4)),
                ('isbn', models.CharField(max_length=50)),
                ('authors', models.ManyToManyField(to='material_data.Author')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_data.editorial')),
            ],
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50)),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('is_rent', models.BooleanField(default=False)),
                ('is_reserve', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.library')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.rack')),
            ],
        ),
    ]
