# Generated by Django 3.2 on 2022-05-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='publication_date',
            field=models.DateField(),
        ),
    ]
